import Head from 'next/head'
import HomePage from '/components/HomePage'

export default function Home() {
  
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://use.fontawesome.com/releases/v5.15.4/css/svg-with-js.css" rel="stylesheet"></link>
      </Head>

      <HomePage  />
      
    </div>
  )
}
